// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import (
	marvel "github.com/gkatanacio/marvel-characters-api/internal/marvel"
	mock "github.com/stretchr/testify/mock"
)

// Cacher is an autogenerated mock type for the Cacher type
type Cacher struct {
	mock.Mock
}

// GetCharacterIds provides a mock function with given fields:
func (_m *Cacher) GetCharacterIds() marvel.IntSet {
	ret := _m.Called()

	var r0 marvel.IntSet
	if rf, ok := ret.Get(0).(func() marvel.IntSet); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(marvel.IntSet)
	}

	return r0
}

// SetCharacterIds provides a mock function with given fields: charIds
func (_m *Cacher) SetCharacterIds(charIds marvel.IntSet) {
	_m.Called(charIds)
}
