// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import (
	marvel "github.com/gkatanacio/marvel-characters-api/internal/marvel"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// CharacterCache is an autogenerated mock type for the CharacterCache type
type CharacterCache struct {
	mock.Mock
}

// GetCharacterIds provides a mock function with given fields:
func (_m *CharacterCache) GetCharacterIds() (marvel.IntSet, time.Time) {
	ret := _m.Called()

	var r0 marvel.IntSet
	if rf, ok := ret.Get(0).(func() marvel.IntSet); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(marvel.IntSet)
	}

	var r1 time.Time
	if rf, ok := ret.Get(1).(func() time.Time); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	return r0, r1
}

// SetCharacterIds provides a mock function with given fields: charIds, latestModified
func (_m *CharacterCache) SetCharacterIds(charIds marvel.IntSet, latestModified time.Time) {
	_m.Called(charIds, latestModified)
}
